name: Publish package to the Maven Central Repository

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Rewrite version for release
        if: ${{ github.event_name == 'release' }}
        run: |
          RELEASE_VERSION="${RELEASE_TAG#v}"
          echo "running for release -> set pom.xml <version> to $RELEASE_VERSION"
          mvn -q versions:set -DnewVersion="$RELEASE_VERSION"
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: Publish package
        run: mvn -q -B -P publish deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
